version: '3.9'

services:
  force-clone:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/optimism:/app/data/optimism
      - ./data/op-geth:/app/data/op-geth
    env_file: .env

  op-geth:
    build:
      context: .
      dockerfile: Dockerfile.services
      args:
        ENTRYPOINT_SCRIPT: op-geth.sh
    volumes:
      - ./data/op-geth:/app/data/op-geth
    depends_on:
      force-clone:
        condition: service_completed_successfully
    env_file: .env
    ports:
      - "8545:8545"
      - "8551:8551"

  op-node:
    build:
      context: .
      dockerfile: Dockerfile.services
      args:
        ENTRYPOINT_SCRIPT: op-node.sh
    volumes:
      - ./data/optimism:/app/data/optimism
    depends_on:
      - op-geth
    env_file: .env
    ports:
      - "8547:8547"

  op-batcher:
    build:
      context: .
      dockerfile: Dockerfile.services
      args:
        ENTRYPOINT_SCRIPT: op-batcher.sh
    volumes:
      - ./data/optimism:/app/data/optimism
    depends_on:
      - op-geth
      - op-node
    env_file: .env
    ports:
      - "8548:8548"

  op-proposer:
    build:
      context: .
      dockerfile: Dockerfile.services
      args:
        ENTRYPOINT_SCRIPT: op-proposer.sh
    volumes:
      - ./data/optimism:/app/data/optimism
    depends_on:
      - op-geth
      - op-node
      # - op-batcher
    env_file: .env
    ports:
      - "8560:8560"
