services:
  force-clone:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/optimism:/app/data/optimism
      - ./data/op-geth:/app/data/op-geth
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/prepare_complete.flag"]
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 30s

  op-geth:
    build:
      context: .
      dockerfile: Dockerfile.services
    volumes:
      - ./data/op-geth:/app/op-geth
    entrypoint: ./entrypoints/op-geth.sh
    depends_on:
      force-clone:
        condition: service_healthy
    ports:
      - "8545:8545"
      - "8551:8551"

  op-node:
    build:
      context: .
      dockerfile: Dockerfile.services
    volumes:
      - ./data/optimism/op-node:/app/op-node
    entrypoint: ./entrypoints/op-node.sh
    depends_on:
      - op-geth
    ports:
      - "8547:8547"

  op-batcher:
    build:
      context: .
      dockerfile: Dockerfile.services
    volumes:
      - ./data/optimism/op-batcher:/app/op-batcher
    entrypoint: ./entrypoints/op-batcher.sh
    depends_on:
      - op-geth
      - op-node
    ports:
      - "8548:8548"

  op-proposer:
    build:
      context: .
      dockerfile: Dockerfile.services
    volumes:
      - ./data/optimism/op-proposer:/app/op-proposer
    entrypoint: ./entrypoints/op-proposer.sh
    depends_on:
      - op-geth
      - op-node
      - op-batcher
    ports:
      - "8560:8560"
